version: '3.4'

services:
  messageserver:
    image: ${DOCKER_REGISTRY-}messageserver
    build:
      context: .
      dockerfile: Dockerfile
      
  pg_db:
    image: postgres
    restart: unless-stopped
    container_name: users
    env_file:
      - .env
    ports:
      - "0.0.0.0:5432:5432"