version: '3.4'

services:
  messageserver:
    image: ${DOCKER_REGISTRY-}messageserver
    environment:
    - ASPNETCORE_URLS=http://+:80
    ports:
       - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    links:
       - pg_db
    depends_on:
       - "pg_db"
    networks:
       - mynetwork
     
  pg_db:
    image: postgres
    container_name: users
    restart: always
    environment:
        POSTGRES_PASSWORD: shz788
        POSTGRES_DB: messendbase
        POSTGRES_HOST: users
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
     driver: bridge